課題が概ね完了。レビューお願いします。
dobocreate/training pull request #2
Opened 2024-08-06 09:30 UTC by dobocreate

2024-08-06 11:56 UTC, chronoll requested changes
全体的によくできています！
指摘箇所について修正した後、同じブランチ内にコミットしてください。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.html
> +                        <li>ドボクリエイト株式会社</li>
liタグはol, ul, menuタグの子要素として使う必要があるので、ここで使うのは不適切かなと思います。
参考：https://developer.mozilla.org/ja/docs/Web/HTML/Element/li

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.html
> +
CSS同様、基本的に改行が2つ以上連続しないようにしてください。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +.news_a_article {
クラス名の_a_の部分が何を指しているかわかりにくいです。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.html
> +        <div class="under_line"></div>
under_lineというクラスがCSSに見つかりませんが、消し忘れであれば消しておいてください。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.html
> +                    <li class="details_factor">財務</li>
先述の通り、liタグはol, ul, menuタグの子要素である必要があります。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +    grid-template-columns:  1fr 1fr 8fr 8fr 1fr 1fr;
information_sectionにおいて、すべての子要素をgridで管理する必要はないかなと思います。これがだめなわけでなく、もっとシンプルに書けるよ、ということです！

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +    grid-template-columns:  1fr 1fr 8fr 8fr 1fr 1fr;
基本的には良くできていると思うので、特段指摘がない場合は修正しなくて大丈夫です。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +.information_botan {
「詳細はこちら」のボタンにおいて、それぞれのinformation_sectionの余白に対して、左に寄りすぎているように見えます。
黄色部分の余白が無くなるようにすると、よりきれいに見えると思います。
![image](https://github.com/user-attachments/assets/c2b9f243-2e30-4c1c-9aba-c9ef5aec0ea0)

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +.information_botan {
また、元のホームページ同様、角を少し丸めてみてください。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +    grid-template-columns:  1fr 1fr 8fr 8fr 1fr 1fr;
余裕があれば、枠線の角を丸めて太さや色をホームページに近づけてください。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +.message_status{
「ドボクリエイト株式会社 ～」の部分において、文字がまだ左に寄っているので、右寄せに修正してください。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +.details_factor{
ホームページでは、下線の左端に対して、文字が少し右にあると思います。同じになるように修正してみてください。
このとき、marginとpaddingどちらを、どこに設定すればいいか、すぐイメージできるようになっていてほしいです。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +.recent_posts_section{
画像のように、文章の上に日付とタグが横に並ぶよう実装してください。適切な配置がすぐ思い浮かぶくらいになっておいてほしいと思います。
![image](https://github.com/user-attachments/assets/c1a9c38f-126c-4912-a3f8-1694c0838b48)

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +.news_title {
見出しのタイトルが太いので(h6タグだから？)、CSSによってホームページと同じくらいの太さにしておいてください。

2024-08-06 11:56 UTC, chronoll commented on michida_html_css/html_practice.css
> +.morimoto_photo{
余裕があれば、画像の角を丸めるようにしてください。

2024-08-06 12:01 UTC, chronoll requested changes
reviewのテスト

2024-08-07 05:32 UTC, dobocreate commented on michida_html_css/html_practice.css
> +.news_a_article {
一応、１つの記事を表示するブロック、という意味合いでaを付けました。

2024-08-09 03:01 UTC, chronoll requested changes
デザイン・レイアウトについては良くできていると思います。
最後にコードの細かい修正を行って、同じようにレビューをリクエストしておいてください。お疲れ様でした。

2024-08-09 07:33 UTC, chronoll approved these changes
修正確認しました。これで課題は完成とします、お疲れさまでした。
自分でマージをしておいてください。

2024-08-09 07:42 UTC, merged